sudo: required

language: generic

services:
  - docker

script:
  - mvn package sonar:sonar -Dsonar.organization=avolpe-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -DDsonar.branch.name=${TRAVIS_PULL_REQUEST_BRANCH:-TRAVIS_BRANCH}
  - docker build -t avolpe/cotizacion .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push avolpe/cotizacion;
    curl $WEBHOOK;
    fi

